export const response = {
  Title: "Scream: The TV Series",
  Year: "2015–2019",
  Rated: "TV-14",
  Released: "30 Jun 2015",
  Runtime: "45 min",
  Genre: "Comedy, Crime, Drama",
  Director: "N/A",
  Writer: "Jay Beattie, Jill E. Blotevogel, Dan Dworkin",
  Actors: "Willa Fitzgerald, Bex Taylor-Klaus, John Karna",
  Plot: "A serialized anthology series that follows a group of teenagers being targeted by a masked serial killer.",
  Language: "English",
  Country: "United States",
  Awards: "3 wins & 10 nominations",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BNjVmY2M3ZTUtMDhkZC00ODk4LTkwMjktNDRjNGRjYTIxZGZiXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
  Ratings: [
    {
      Source: "Internet Movie Database",
      Value: "7.1/10",
    },
  ],
  Metascore: "N/A",
  imdbRating: "7.1",
  imdbVotes: "38,066",
  imdbID: "tt3921180",
  Type: "series",
  totalSeasons: "3",
  Response: "True",
};
